"""
Firebase Uploader — pushes ML pipeline results to Firestore.

Collections created:
  • shipments        – raw shipment records (from live or training data)
  • alerts           – risk alerts generated by the scoring engine
  • recommendations  – intervention recommendations
  • metrics          – single doc with aggregated risk analytics
"""

import os, json, ast
import pandas as pd
import numpy as np
import firebase_admin
from firebase_admin import credentials, firestore

# ── Paths ────────────────────────────────────────────────────────────────────
PROJECT_DIR  = os.path.dirname(os.path.abspath(__file__))
DATA_DIR     = os.path.join(PROJECT_DIR, "data")
OUTPUT_DIR   = os.path.join(PROJECT_DIR, "outputs")
ARTIFACTS_DIR = os.path.join(PROJECT_DIR, "artifacts")
SERVICE_KEY  = os.path.join(PROJECT_DIR, "serviceAccountKey.json")


def _init_firebase():
    """Initialize Firebase Admin SDK (idempotent)."""
    if not firebase_admin._apps:
        cred = credentials.Certificate(SERVICE_KEY)
        firebase_admin.initialize_app(cred)
    return firestore.client()


def _clean_value(v):
    """Convert numpy/pandas types to native Python for Firestore."""
    if isinstance(v, (np.integer,)):
        return int(v)
    if isinstance(v, (np.floating,)):
        return float(v)
    if isinstance(v, (np.bool_,)):
        return bool(v)
    if isinstance(v, float) and (np.isnan(v) or np.isinf(v)):
        return None
    if pd.isna(v):
        return None
    return v


def _clean_record(record: dict) -> dict:
    """Recursively clean a dict for Firestore compatibility."""
    return {k: _clean_value(v) for k, v in record.items()}


def _parse_list_field(value):
    """Parse stringified Python lists (e.g. from CSV) back into real lists."""
    if isinstance(value, list):
        return value
    if pd.isna(value) or value is None:
        return []
    try:
        parsed = ast.literal_eval(str(value))
        return parsed if isinstance(parsed, list) else [str(value)]
    except Exception:
        return [str(value)]


# ── Upload Functions ─────────────────────────────────────────────────────────

def upload_shipments(db):
    """Upload shipment records to Firestore 'shipments' collection."""
    # Prefer live shipments, fall back to raw training data
    live_path = os.path.join(DATA_DIR, "live_shipments.csv")
    raw_path  = os.path.join(DATA_DIR, "shipments_raw.csv")

    if os.path.exists(live_path):
        df = pd.read_csv(live_path)
        source = "live_shipments.csv"
    elif os.path.exists(raw_path):
        df = pd.read_csv(raw_path)
        source = "shipments_raw.csv"
    else:
        print("[Upload] No shipment data found. Run the pipeline first.")
        return 0

    coll = db.collection("shipments")

    # Batch writes (max 500 per batch)
    batch = db.batch()
    count = 0

    for _, row in df.iterrows():
        record = _clean_record(row.to_dict())
        doc_ref = coll.document(record["shipment_id"])
        batch.set(doc_ref, record)
        count += 1

        if count % 450 == 0:  # commit before 500 limit
            batch.commit()
            batch = db.batch()

    batch.commit()
    print(f"[Upload] Shipments: {count} docs from {source}")
    return count


def upload_alerts(db):
    """Upload alert records to Firestore 'alerts' collection."""
    alerts_path = os.path.join(OUTPUT_DIR, "alerts.csv")
    if not os.path.exists(alerts_path):
        print("[Upload] No alerts.csv found. Run the pipeline first.")
        return 0

    df = pd.read_csv(alerts_path)
    coll = db.collection("alerts")

    batch = db.batch()
    count = 0

    for _, row in df.iterrows():
        record = _clean_record(row.to_dict())
        # Parse stringified list fields
        record["top_risk_factors"] = _parse_list_field(record.get("top_risk_factors"))
        doc_ref = coll.document(record["shipment_id"])
        batch.set(doc_ref, record)
        count += 1

        if count % 450 == 0:
            batch.commit()
            batch = db.batch()

    batch.commit()
    print(f"[Upload] Alerts: {count} docs")
    return count


def upload_recommendations(db):
    """Upload recommendation records to Firestore 'recommendations' collection."""
    recs_path = os.path.join(OUTPUT_DIR, "recommendations.csv")
    if not os.path.exists(recs_path):
        print("[Upload] No recommendations.csv found. Run the pipeline first.")
        return 0

    df = pd.read_csv(recs_path)
    coll = db.collection("recommendations")

    batch = db.batch()
    count = 0

    for _, row in df.iterrows():
        record = _clean_record(row.to_dict())
        # Parse stringified list fields
        record["reasoning"] = _parse_list_field(record.get("reasoning"))
        doc_ref = coll.document(record["shipment_id"])
        batch.set(doc_ref, record)
        count += 1

        if count % 450 == 0:
            batch.commit()
            batch = db.batch()

    batch.commit()
    print(f"[Upload] Recommendations: {count} docs")
    return count


def upload_metrics(db):
    """Compute and upload aggregated risk metrics to Firestore 'metrics/summary'."""
    live_path = os.path.join(DATA_DIR, "live_shipments.csv")
    raw_path  = os.path.join(DATA_DIR, "shipments_raw.csv")
    alerts_path = os.path.join(OUTPUT_DIR, "alerts.csv")

    # Load shipments
    if os.path.exists(live_path):
        ship_df = pd.read_csv(live_path)
    elif os.path.exists(raw_path):
        ship_df = pd.read_csv(raw_path)
    else:
        ship_df = pd.DataFrame()

    # Load alerts
    if os.path.exists(alerts_path):
        alert_df = pd.read_csv(alerts_path)
    else:
        alert_df = pd.DataFrame()

    total = len(ship_df)
    metrics = {
        "total_shipments": total,
        "critical_alerts": int((alert_df["risk_tier"] == "CRITICAL").sum()) if not alert_df.empty else 0,
        "high_alerts":     int((alert_df["risk_tier"] == "HIGH").sum()) if not alert_df.empty else 0,
        "medium_alerts":   int((alert_df["risk_tier"] == "MEDIUM").sum()) if not alert_df.empty else 0,
        "low_alerts":      int((alert_df["risk_tier"] == "LOW").sum()) if not alert_df.empty else 0,
        "average_risk_score": round(float(ship_df["delay_probability"].mean()), 4) if not ship_df.empty else 0.0,
        "shipments_at_risk":  int((ship_df["delay_probability"] >= 0.5).sum()) if not ship_df.empty else 0,
    }

    db.collection("metrics").document("summary").set(metrics)
    print(f"[Upload] Metrics: {metrics}")
    return metrics


# ── Main Entry Point ─────────────────────────────────────────────────────────

def upload_all():
    """Run all uploads to Firestore."""
    print("\n" + "=" * 60)
    print("  FIREBASE UPLOAD — Pushing data to Firestore")
    print("=" * 60)

    db = _init_firebase()

    upload_shipments(db)
    upload_alerts(db)
    upload_recommendations(db)
    upload_metrics(db)

    print("\n[Upload] All data uploaded to Firestore successfully.")


if __name__ == "__main__":
    upload_all()
